## spark session
app_name: 'Multi-task Demo ESMM'
local: True
worker_count: 10
server_count: 2
batch_size: 256
worker_memory: '10G'
server_memory: '20G'
coordinator_memory: '10G'
local_spark: local

## datasets
train_path_prefix: /data/walter/ruf/parquet/
train_start_date: 2025-05-17
train_end_date: 2025-05-17
validation_date: 2025-05-18
movas_log_output_path: ./log/movas.log

## model configurations
column_name_path: /data/walter/ruf/column_name.ruf_v1
combine_schema_path: ./conf/combine_schema.ruf
# wide_combine_schema_path: ./conf/combine_schema.ruf

model_in_path: null
model_out_base_path: ./output/
model_export_path: null
model_version: '0.1'
experiment_name: ruf_outer_esmm
metric_update_interval: 100

## model hyper params
ctcvr_loss_weight: 1.0
ctr_loss_weight: 1.0
embedding_size: 8
adam_learning_rate: 0.00001
ftrl_l1: 0.1
ftrl_l2: 10.0
ftrl_alpha: 0.005
ftrl_beta: 0.05
dnn_hidden_units: [512, 256, 64]
sparse_init_var: 0.01
dnn_hidden_activations: relu
use_bias: True
batch_norm: False
net_dropout: 0.5
net_regularizer: null
training_epoches: 1
shuffle_training_dataset: True
