fir=0.09
fft=0
pos_weight=1.1
model=/Users/yeahmobi/Desktop/movas/01_project/lr_ftrl/ftrl_maven-master/train_output/none
output=/Users/yeahmobi/Desktop/movas/01_project/lr_ftrl/ftrl_maven-master/train_output
conf=/Users/yeahmobi/Desktop/movas/01_project/lr_ftrl/ftrl_maven-master/conf/para.conf
