fir=0.3
fft=6
pos_weight=1
model=./train_output/base
output=./train_output
conf=./conf/para.conf
name=purchase_train
label=purchase
model_type=cvr
click_label=click_label
keys=demand_pkgname,business_type
