# MetaSpore TrainFlows Package
# Generated by migration script

from .base import BaseTrainFlow
from .dnn import DNNTrainFlow
from .mtl import MTLTrainFlow

# Conditional imports for optional trainflows
try:
    from .defer import DeferTrainFlow
except ImportError:
    pass

try:
    from .delf import DELFModelTrainFlow
    # Provide alias for consistency
    DELFTrainFlow = DELFModelTrainFlow
except ImportError:
    pass

try:
    from .ltv import LtvModelTrainFlow
    # Provide alias for consistency
    LTVTrainFlow = LtvModelTrainFlow
except ImportError:
    pass

try:
    from .mdl import MDLModelTrainFlow
    # Provide alias for consistency
    MDLTrainFlow = MDLModelTrainFlow
except ImportError:
    pass

try:
    from .winrate import WinrateModelTrainFlow
    # Provide alias for consistency
    WinRateTrainFlow = WinrateModelTrainFlow
except ImportError:
    pass

try:
    from .metacpl import MetaCPLTrainFlow
except ImportError:
    pass

# Additional optional imports
try:
    from .dense_feature import DenseFeatureUtil
except ImportError:
    pass

try:
    from .widedeep_net import WideDeep
except ImportError:
    pass
